### ISSUE TITLE
Possible bug with cached_predict

### ISSUE THREAD

**Issue by DataDaveH** [IndicoDataSolutions/finetune#206] opened 2018-12-08 21:35 UTC
**Describe the bug**
I can't get `cached_predict()` to work properly. After the first call to `predict()`, the inference time is lightning fast, but the last value from the first call is used for all inference from then on. (see attached screenshot)

**Minimum Reproducible Example**
```
model = Classifier().load("path_to_model_file")
with model.cached_predict():
    print(model.predict_proba(["some text"]))
    print(model.predict_proba(["some other text for different probs"]))
```

**Expected behavior**
The inference time is significantly faster starting with the second predict and it predicts for the given input.

**Additional context**
This seems to work on CPU, but not on GPU. This was run on several AWS instance types for CPU performance and a p2.xlarge for GPU testing. 
I'm using the Deep Learning AMI (Ubuntu) Version 19.0 - ami-05bc59103c52af154
Then I am pulling the development branch of finetune.
I tried with and without trying to upgrade tensorflow with no difference in performance.

**Screen Shot**  
* Notice that in the first example all predicted probabilities are different, and in the second example, all predicted probabilities match the first call.
![cached_predict_bug](https://user-images.githubusercontent.com/25015275/49690935-8fb50b00-faed-11e8-85c2-210974081bab.png)

**Comment by benleetownsend** [comment] 2018-12-10 12:02
Thanks for the very thorough report. I can confirm that I am able to reproduce and believe I understand the cause. I'm working on a fix for this as we speak and have added a test to reflect this. I will tag the pull request when this is ready.

**Comment by benleetownsend** [comment] 2018-12-10 13:03
@DataDaveH I have a proposed fix in #207. Let me know if this does not fix your problem. 

Can I confirm that on CPU you had a batch size of 1? 

If this is not the case then I may need to do a little more digging as the fix I have does not align with your observation of functionality on CPU and not GPU.

**Comment by DataDaveH** [comment] 2018-12-10 21:22
I had the default batch size, so it was 2. Either way, I pulled the fix and it resolved the problem. Thank you!

**Comment by benleetownsend** [comment] 2018-12-11 11:59
Thanks for the bug report and for verifying my fix.

**Closed by benleetownsend** 2018-12-11 11:59 UTC
