### ISSUE TITLE
Shapes are always computed; don't use the compute_shapes as it has no effect.

### ISSUE THREAD

**Issue by dimidd** [IndicoDataSolutions/finetune#154] opened 2018-10-09 14:41 UTC
**Describe the bug**
I get the following warning both in training and prediction:
```
WARNING:tensorflow:From ~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/function.py:986: calling Graph.create_op (from tensorflow.python.framework.ops) with compute_shapes is deprecated and will be removed in a future version.
Instructions for updating:
Shapes are always computed; don't use the compute_shapes as it has no effect.
```

**Minimum Reproducible Example**
```
[... train a classifier as in the examples and save it ...]
model = ft.Classifier.load(PATH)
model.predict(X_test)
```

**Expected behavior**
No warnings

**Comment by madisonmay** [comment] 2018-10-09 17:45
Hi @dimidd,

Thanks for the bug report.  In this particular case the warning being raised is actually caused by tensorflow using it's own deprecated API, so the only way for us to disable the warning is to explicitly silence deprecation warnings like this.  For now I'm going to mark this as wontfix, but we're in the middle of a rather large codebase refactor and after that merge we'll be avoiding the part of the tf codebase that causes this annoying message anyhow -- so a patch for this coming with finetune 0.5.0.

**Closed by madisonmay** 2018-10-09 17:45 UTC
Labels: wontfix
